name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        cd ../api
        npm install
    
    - name: Run frontend tests
      run: |
        cd frontend
        npm test
    
    - name: Run API tests
      run: |
        cd api
        npm test
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Build API
      run: |
        cd api
        npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        cd ../api
        npm install
    
    - name: Build and deploy frontend
      run: |
        cd frontend
        npm run build
        # Adicionar comando de deploy do frontend aqui
    
    - name: Build and deploy API
      run: |
        cd api
        npm run build
        # Adicionar comando de deploy da API aqui 